### ISSUE TITLE
Flux插件调用成功但出现报错提示（已扣费，不显示生成的图）

### ISSUE THREAD

**Issue by ice-lemon** [ChatGPTNextWeb/NextChat-Awesome-Plugins#13]
{
  "error": {
    "code": "invalid_type",
    "message": "Provider API error: Invalid type for 'messages[2].content': expected one of a string or array of objects, but got an object instead. (request id: 20241010110629401726356c7asgQY7)",
    "param": "messages[2].content",
    "type": "invalid_request_error"
  }
}

**Comment by ice-lemon** [comment]
![image](https://github.com/user-attachments/assets/39ff1077-060a-488f-8437-1f999556d758)

**Comment by lloydzhou** [comment]
v2.15.4版本插件运行的地方有bug
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5614

在 app.nextchat.dev 这个在线版本已经修复。app版以及docker版本需等待下一个版本发布会修复这个问题

**Comment by ice-lemon** [comment]
好的，感谢
