### ISSUE TITLE
plugins入口找不到，添加的插件会消失

### ISSUE THREAD

**Issue by zhang-qihao** [ChatGPTNextWeb/NextChat-Awesome-Plugins#14]
nextgpt版本为v2.15.4，plugins配置的入口在哪
我使用url进入插件配置的界面虽然可以正常添加插件，但是添加的插件在使用一段时间过后，就会消失掉。如何统一添加插件使得所有浏览器都可以使用新增的插件。

**Comment by lloydzhou** [comment]
这些数据，都在本地存储里面，使用过程中如果清除浏览器数据会导致数据丢失。

**Comment by zhang-qihao** [comment]
请问服务端能配置吗

**Comment by lloydzhou** [comment]
开源版本用户数据是存本地的。
官方的企业版本，数据是存服务器的。

**Comment by zhang-qihao** [comment]
好的感谢🙏

**Comment by zhang-qihao** [comment]
好的感谢🙏
