### ISSUE TITLE
请问各位大佬，插件dalle3的token填什么信息？没找到类似key的内容。。

### ISSUE THREAD

**Issue by qiq777** [ChatGPTNextWeb/NextChat-Awesome-Plugins#15]
![image](https://github.com/user-attachments/assets/0cd7dcc4-4c57-4aba-9a18-597470361033)

**Comment by doctorgreen4721** [comment]
token就输入你的api key，还有如果用的不是openai的官方api记得把下面插件里面的url也改一下。

**Comment by qiq777** [comment]
用openai的api key是叭，好的好的，感谢大佬~
