### ISSUE TITLE
无法使用插件

### ISSUE THREAD

**Issue by Arthur409** [ChatGPTNextWeb/NextChat-Awesome-Plugins#6]
使用vercel配置，按照步骤配置插件后会出现格式错误的弹窗，无法使用插件
<img width="918" alt="image" src="https://github.com/user-attachments/assets/67700ffe-c194-412d-a7a5-e4fc8c4e9445">
<img width="973" alt="image" src="https://github.com/user-attachments/assets/6ce7e4bf-8154-47de-af7e-20abd7420d26">

**Comment by Arthur409** [comment]
arxiv这个插件没问题，dalle有问题，不知道是不是我配置的不对

**Comment by Arthur409** [comment]
好像不需要授权的插件就没有问题，授权方式选择其他就会出现格式错误，请问是我哪里的配置有问题嘛

**Comment by lloydzhou** [comment]
需要授权的插件，要填写自己的apikey
